<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$showNewsletter = $helper->getConfigValue('shopkartlitesettings/newsletter_settings/enable');
$showFooterColumns = $helper->getConfigValue('shopkartlitesettings/footer_columns/enable_footer_columns');
$footerStColumn = $helper->getConfigValue('shopkartlitesettings/footer_columns/footer_st_column');
$footerNdColumn = $helper->getConfigValue('shopkartlitesettings/footer_columns/footer_nd_column');
$footerRdColumn = $helper->getConfigValue('shopkartlitesettings/footer_columns/footer_rd_column');
$footerThColumn = $helper->getConfigValue('shopkartlitesettings/footer_columns/footer_th_column');
$address = $helper->getConfigValue('shopkartlitesettings/footer_contant/address');
$email = $helper->getConfigValue('shopkartlitesettings/footer_contant/email');
$phone = $helper->getConfigValue('shopkartlitesettings/footer_contant/phone');
$enableFooterBottom = $helper->getConfigValue('shopkartlitesettings/footer_bottom/enable_footer_bottom');
$copyrightText = $helper->getConfigValue('shopkartlitesettings/footer_bottom/copyright_text');
$copyrightRightBlock = $helper->getConfigValue('shopkartlitesettings/footer_bottom/copyright_right_block');
?>
<div class="footer-top">   
    <?php if ($showFooterColumns) { ?>
        <div class="footer-links">
            <div class="page-main">
                <div class="footer-links-main">                    
                    <div class="footer-links-column column1">                        
                        <?php if ($footerStColumn != '') { ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerStColumn)->toHtml(); ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column column2">                        
                        <?php if ($footerNdColumn != '') { ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerNdColumn)->toHtml(); ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column column3">
                        <?php if ($footerRdColumn != '') { ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerRdColumn)->toHtml(); ?>
                        <?php } ?>
                    </div>
                    <div class="footer-links-column column4">
                        <?php if ($footerThColumn != '') { ?>
                            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($footerThColumn)->toHtml(); ?>
                        <?php } ?>
                    </div>                    
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<?php if ($enableFooterBottom) { ?>
    <div class="footer-bottom">
        <div class="page-main">
            <div class="copuright-outer">
                <small class="copyright">
                    <span><?php /* @escapeNotVerified */ echo $copyrightText; ?></span>
                </small>
                <?php if ($copyrightRightBlock != '') { ?>
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($copyrightRightBlock)->toHtml(); ?>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>